'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://tempuri.org/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/altaPersona", ReplyAction:="*")>  _
        Function altaPersona(ByVal request As ServiceReference1.altaPersonaRequest) As ServiceReference1.altaPersonaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/bajaPersona", ReplyAction:="*")>  _
        Function bajaPersona(ByVal id_persona As Integer) As Boolean
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAll", ReplyAction:="*")>  _
        Function getAll(ByVal request As ServiceReference1.getAllRequest) As ServiceReference1.getAllResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarPersona", ReplyAction:="*")>  _
        Function modificarPersona(ByVal request As ServiceReference1.modificarPersonaRequest) As ServiceReference1.modificarPersonaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class altaPersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="altaPersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.altaPersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.altaPersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class altaPersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombreApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public fechaNacimiento As Date
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public edad As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public sexo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer)
            MyBase.New
            Me.nombreApellido = nombreApellido
            Me.fechaNacimiento = fechaNacimiento
            Me.edad = edad
            Me.sexo = sexo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class altaPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="altaPersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.altaPersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.altaPersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class altaPersonaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public altaPersonaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal altaPersonaResult As Boolean)
            MyBase.New
            Me.altaPersonaResult = altaPersonaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAllRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAll", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.getAllRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.getAllRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class getAllRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAllResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAllResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.getAllResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.getAllResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getAllResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getAllResult As ServiceReference1.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getAllResult As ServiceReference1.ArrayOfString)
            MyBase.New
            Me.getAllResult = getAllResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class modificarPersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="modificarPersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.modificarPersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.modificarPersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class modificarPersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id_persona As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombreApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public fechaNacimiento As Date
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public edad As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public sexo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id_persona As Integer, ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer)
            MyBase.New
            Me.id_persona = id_persona
            Me.nombreApellido = nombreApellido
            Me.fechaNacimiento = fechaNacimiento
            Me.edad = edad
            Me.sexo = sexo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class modificarPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="modificarPersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.modificarPersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.modificarPersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class modificarPersonaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public modificarPersonaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal modificarPersonaResult As Boolean)
            MyBase.New
            Me.modificarPersonaResult = modificarPersonaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ServiceSoap)
        Implements ServiceReference1.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ServiceSoap_altaPersona(ByVal request As ServiceReference1.altaPersonaRequest) As ServiceReference1.altaPersonaResponse Implements ServiceReference1.ServiceSoap.altaPersona
            Return MyBase.Channel.altaPersona(request)
        End Function
        
        Public Function altaPersona(ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer) As Boolean
            Dim inValue As ServiceReference1.altaPersonaRequest = New ServiceReference1.altaPersonaRequest()
            inValue.Body = New ServiceReference1.altaPersonaRequestBody()
            inValue.Body.nombreApellido = nombreApellido
            inValue.Body.fechaNacimiento = fechaNacimiento
            inValue.Body.edad = edad
            inValue.Body.sexo = sexo
            Dim retVal As ServiceReference1.altaPersonaResponse = CType(Me,ServiceReference1.ServiceSoap).altaPersona(inValue)
            Return retVal.Body.altaPersonaResult
        End Function
        
        Public Function bajaPersona(ByVal id_persona As Integer) As Boolean Implements ServiceReference1.ServiceSoap.bajaPersona
            Return MyBase.Channel.bajaPersona(id_persona)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ServiceSoap_getAll(ByVal request As ServiceReference1.getAllRequest) As ServiceReference1.getAllResponse Implements ServiceReference1.ServiceSoap.getAll
            Return MyBase.Channel.getAll(request)
        End Function
        
        Public Function getAll() As ServiceReference1.ArrayOfString
            Dim inValue As ServiceReference1.getAllRequest = New ServiceReference1.getAllRequest()
            inValue.Body = New ServiceReference1.getAllRequestBody()
            Dim retVal As ServiceReference1.getAllResponse = CType(Me,ServiceReference1.ServiceSoap).getAll(inValue)
            Return retVal.Body.getAllResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ServiceSoap_modificarPersona(ByVal request As ServiceReference1.modificarPersonaRequest) As ServiceReference1.modificarPersonaResponse Implements ServiceReference1.ServiceSoap.modificarPersona
            Return MyBase.Channel.modificarPersona(request)
        End Function
        
        Public Function modificarPersona(ByVal id_persona As Integer, ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer) As Boolean
            Dim inValue As ServiceReference1.modificarPersonaRequest = New ServiceReference1.modificarPersonaRequest()
            inValue.Body = New ServiceReference1.modificarPersonaRequestBody()
            inValue.Body.id_persona = id_persona
            inValue.Body.nombreApellido = nombreApellido
            inValue.Body.fechaNacimiento = fechaNacimiento
            inValue.Body.edad = edad
            inValue.Body.sexo = sexo
            Dim retVal As ServiceReference1.modificarPersonaResponse = CType(Me,ServiceReference1.ServiceSoap).modificarPersona(inValue)
            Return retVal.Body.modificarPersonaResult
        End Function
    End Class
End Namespace
