'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference2
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://tempuri.org/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference2.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/altaPersona", ReplyAction:="*")>  _
        Function altaPersona(ByVal request As ServiceReference2.altaPersonaRequest) As ServiceReference2.altaPersonaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/bajaPersona", ReplyAction:="*")>  _
        Function bajaPersona(ByVal id_persona As Integer) As Boolean
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAll", ReplyAction:="*")>  _
        Function getAll(ByVal request As ServiceReference2.getAllRequest) As ServiceReference2.getAllResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarPersona", ReplyAction:="*")>  _
        Function modificarPersona(ByVal request As ServiceReference2.modificarPersonaRequest) As ServiceReference2.modificarPersonaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class altaPersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="altaPersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.altaPersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.altaPersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class altaPersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombreApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public fechaNacimiento As Date
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public edad As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public sexo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer)
            MyBase.New
            Me.nombreApellido = nombreApellido
            Me.fechaNacimiento = fechaNacimiento
            Me.edad = edad
            Me.sexo = sexo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class altaPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="altaPersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.altaPersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.altaPersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class altaPersonaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public altaPersonaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal altaPersonaResult As Boolean)
            MyBase.New
            Me.altaPersonaResult = altaPersonaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAllRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAll", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.getAllRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.getAllRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class getAllRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getAllResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getAllResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.getAllResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.getAllResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getAllResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getAllResult As ServiceReference2.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getAllResult As ServiceReference2.ArrayOfString)
            MyBase.New
            Me.getAllResult = getAllResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class modificarPersonaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="modificarPersona", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.modificarPersonaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.modificarPersonaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class modificarPersonaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id_persona As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombreApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public fechaNacimiento As Date
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public edad As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public sexo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id_persona As Integer, ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer)
            MyBase.New
            Me.id_persona = id_persona
            Me.nombreApellido = nombreApellido
            Me.fechaNacimiento = fechaNacimiento
            Me.edad = edad
            Me.sexo = sexo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class modificarPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="modificarPersonaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.modificarPersonaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.modificarPersonaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class modificarPersonaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public modificarPersonaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal modificarPersonaResult As Boolean)
            MyBase.New
            Me.modificarPersonaResult = modificarPersonaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits ServiceReference2.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference2.ServiceSoap)
        Implements ServiceReference2.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_ServiceSoap_altaPersona(ByVal request As ServiceReference2.altaPersonaRequest) As ServiceReference2.altaPersonaResponse Implements ServiceReference2.ServiceSoap.altaPersona
            Return MyBase.Channel.altaPersona(request)
        End Function
        
        Public Function altaPersona(ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer) As Boolean
            Dim inValue As ServiceReference2.altaPersonaRequest = New ServiceReference2.altaPersonaRequest()
            inValue.Body = New ServiceReference2.altaPersonaRequestBody()
            inValue.Body.nombreApellido = nombreApellido
            inValue.Body.fechaNacimiento = fechaNacimiento
            inValue.Body.edad = edad
            inValue.Body.sexo = sexo
            Dim retVal As ServiceReference2.altaPersonaResponse = CType(Me,ServiceReference2.ServiceSoap).altaPersona(inValue)
            Return retVal.Body.altaPersonaResult
        End Function
        
        Public Function bajaPersona(ByVal id_persona As Integer) As Boolean Implements ServiceReference2.ServiceSoap.bajaPersona
            Return MyBase.Channel.bajaPersona(id_persona)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_ServiceSoap_getAll(ByVal request As ServiceReference2.getAllRequest) As ServiceReference2.getAllResponse Implements ServiceReference2.ServiceSoap.getAll
            Return MyBase.Channel.getAll(request)
        End Function
        
        Public Function getAll() As ServiceReference2.ArrayOfString
            Dim inValue As ServiceReference2.getAllRequest = New ServiceReference2.getAllRequest()
            inValue.Body = New ServiceReference2.getAllRequestBody()
            Dim retVal As ServiceReference2.getAllResponse = CType(Me,ServiceReference2.ServiceSoap).getAll(inValue)
            Return retVal.Body.getAllResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_ServiceSoap_modificarPersona(ByVal request As ServiceReference2.modificarPersonaRequest) As ServiceReference2.modificarPersonaResponse Implements ServiceReference2.ServiceSoap.modificarPersona
            Return MyBase.Channel.modificarPersona(request)
        End Function
        
        Public Function modificarPersona(ByVal id_persona As Integer, ByVal nombreApellido As String, ByVal fechaNacimiento As Date, ByVal edad As Integer, ByVal sexo As Integer) As Boolean
            Dim inValue As ServiceReference2.modificarPersonaRequest = New ServiceReference2.modificarPersonaRequest()
            inValue.Body = New ServiceReference2.modificarPersonaRequestBody()
            inValue.Body.id_persona = id_persona
            inValue.Body.nombreApellido = nombreApellido
            inValue.Body.fechaNacimiento = fechaNacimiento
            inValue.Body.edad = edad
            inValue.Body.sexo = sexo
            Dim retVal As ServiceReference2.modificarPersonaResponse = CType(Me,ServiceReference2.ServiceSoap).modificarPersona(inValue)
            Return retVal.Body.modificarPersonaResult
        End Function
    End Class
End Namespace
